version: "3.8"

services:
  # consul:
  #   image: hashicorp/consul:1.15.5
  #   command: agent -server -bootstrap-expect=1 -advertise=157.159.160.197 -ui #-client=0.0.0.0 -bind=0.0.0.0
  #   environment:
  #     - CONSUL_BIND_INTERFACE=eth0
  #     - CONSUL_CLIENT_INTERFACE=eth0
  #   ports:
  #     - "8500:8500"
  #     - "8600:8600/udp"
  #   networks:
  #     - my_overlay
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.role==manager
  
  consul:
    image: hashicorp/consul:1.15.5
    # network_mode: "host"
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -advertise=157.159.160.197
    environment:
      - CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt":true}
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - my_overlay
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager

  registry:
    image: registry:2
    ports:
      - 5000:5000            # so manager & worker can talk to it
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - my_overlay
    deploy:
      placement:
        constraints:
          - node.role==manager

networks:
  my_overlay:
    external: true

volumes:
  registry_data: {}
