version: "3.8"

services:
  consul:
    image: hashicorp/consul:latest
    command: agent -server -bootstrap-expect=2 -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - my_overlay
    deploy:
      replicas: 2
networks:
  my_overlay:
    external: true